# Generated by Django 4.1.7 on 2023-03-25 17:45

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("title_tr", models.CharField(max_length=200, null=True)),
                ("title_en", models.CharField(max_length=200, null=True)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("slug_tr", models.SlugField(max_length=200, null=True, unique=True)),
                ("slug_en", models.SlugField(max_length=200, null=True, unique=True)),
                ("is_activate", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cover_image",
                    models.ImageField(blank=True, upload_to="product_category"),
                ),
                ("description", models.CharField(blank=True, max_length=160)),
                (
                    "description_tr",
                    models.CharField(blank=True, max_length=160, null=True),
                ),
                (
                    "description_en",
                    models.CharField(blank=True, max_length=160, null=True),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="product.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
                "unique_together": {("slug", "parent")},
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("title_tr", models.CharField(max_length=200, null=True)),
                ("title_en", models.CharField(max_length=200, null=True)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("slug_tr", models.SlugField(max_length=200, null=True, unique=True)),
                ("slug_en", models.SlugField(max_length=200, null=True, unique=True)),
                ("is_activate", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cover_image", models.ImageField(blank=True, upload_to="product")),
                ("description", models.CharField(blank=True, max_length=160)),
                (
                    "description_tr",
                    models.CharField(blank=True, max_length=160, null=True),
                ),
                (
                    "description_en",
                    models.CharField(blank=True, max_length=160, null=True),
                ),
                ("content", tinymce.models.HTMLField(blank=True, null=True)),
                ("content_tr", tinymce.models.HTMLField(blank=True, null=True)),
                ("content_en", tinymce.models.HTMLField(blank=True, null=True)),
                ("view_count", models.PositiveBigIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="product.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
            ],
        ),
    ]
