# Generated by Django 4.1.7 on 2023-03-28 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0002_page_content_en_page_content_tr_page_slug_en_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="page.page",
                    ),
                ),
            ],
        ),
    ]
