# Generated by Django 4.1.7 on 2023-03-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0003_pageimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="pageimage",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="page"),
        ),
    ]
