# Generated by Django 4.1.7 on 2023-03-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0005_rename_product_pageimage_page"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="İsim Soyisim")),
                (
                    "email",
                    models.EmailField(max_length=150, verbose_name="Email Adresi"),
                ),
                ("subject", models.CharField(max_length=300, verbose_name="Konu")),
                ("message", models.TextField(max_length=2000, verbose_name="Mesaj")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Gönderilme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "İletişim Mesajı",
                "verbose_name_plural": "İletişim Mesajları",
            },
        ),
    ]
