# Generated by Django 4.1.7 on 2023-03-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0006_contactform"),
    ]

    operations = [
        migrations.CreateModel(
            name="CareerForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="İsim Soyisim")),
                (
                    "email",
                    models.EmailField(max_length=150, verbose_name="Email Adresi"),
                ),
                (
                    "phone",
                    models.CharField(max_length=150, verbose_name="Email Adresi"),
                ),
                ("date_of_birth", models.DateField(verbose_name="Doğum Tarihi")),
                ("cv_file", models.FileField(blank=True, upload_to="cv_files")),
                ("subject", models.CharField(max_length=300, verbose_name="Konu")),
                ("content", models.TextField(max_length=2000, verbose_name="Mesaj")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Gönderilme Tarihi"
                    ),
                ),
            ],
        ),
    ]
