# Generated by Django 4.1.7 on 2023-03-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="post"),
        ),
        migrations.AddField(
            model_name="service",
            name="description",
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
