# Generated by Django 4.1.7 on 2023-03-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0002_service_cover_image_service_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="description_en",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="description_tr",
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="service"),
        ),
    ]
